src/App.css, src/App.tsx, src/DisplayTask.css, src/DisplayTask.tsx, src/EditTask.tsx
Display Task displays all task attributes, number of users is only visible if role is super. We will need to modify this file later for allowing the editing of tasks and to adjust the formatting.
=> Solved display task

src/TaskFunctions.ts
Includes first 4 attribute functions, a makeTask function and an addTask function.
=> Task functions

src/DisplayTask.test.tsx
Includes tests for 5 (out of 9) displayed attributes including the presence of the checkbox.
=> Tests display view

src/CentralItemList.test.tsx, src/CentralItemList.tsx
Tests for the central item list include a test for displaying the entire list, three tests for presence/absence of an addTask button and two tests for the presence/absence of an addUser button.
=> Tests central item list

src/TaskFunctions.ts
Added the middle and ending attribute functions for the task interface.
=> Middle and End task attribute functions

src/TaskFunctions.test.ts
tests for setSteps, setNumUsers, and setTime. Note we may want to make time a string
=> Task functions tests

src/App.tsx
=> Sullivank210 add name

src/App.tsx
=> Aoster@udel.edu/aaron oster

src/DisplayTask.test.tsx
I added the missing tests for displayTask
=> added two more tests to displayTask

src/App.tsx, src/list-components/UserList.tsx
I wrote the user list and called it in app. I changed the user list of the initial state of user1 to a list of two tasks to be able to see the functionality of user list. I also deleted the old example of how to use displayView to avoid confusion.
=> Cmeiss user list

src/list-components/UserList.test.tsx
Added five tests for the user list
=> Cmeiss tests user list

src/App.css, src/App.tsx, src/list-components/UserList.css, src/list-components/UserList.tsx, src/list-components/adminList.css, src/list-components/adminlist.tsx
I added CSS files for both the admin and the user list and moved the instructions for the black frame around the list from the app.css file into the css file for the two components.
=> Removed emtpy black frames from Admin and User List

src/App.tsx, src/editing-components/EditTime.tsx
I added the edit time component. Since the state is not yet passed through all files, the edit time component is not connected to edit task and not displayed.
=> Cmeiss edit time

src/list-components/AddUser.test.tsx
added tests for the addUser piece of modifyUsers. still need to check if it actually changes the roles
=> Sullivank add user tests

src/TASKS.tsx, src/editing-components/EditTime.tsx
Added some formatting rules to display military time with a colon
=> Cmeiss connect edit time

src/list-components/UserList.tsx
Fixed the rerendering issue after changing attributes of the tasks.
=> fixed missing rerendering after changes in tasks

src/App.tsx, src/list-components/DisplayTask.tsx, src/list-components/UserList.tsx, src/list-components/adminlist.tsx, src/user-functions.ts
dnd works in theory for all lists. none of the lists actually change yet and it is still unconditional for admin list
=> Sullivank new dnd

src/App.tsx, src/list-components/UserList.test.tsx, src/list-components/UserList.tsx
Connected the actual userList to the UserList component, so that the userList of the current user is displayed. All changes made in the userList are now only editing the userList of the current user, changes do not get lost when we change the role.
=> Displaying User List

src/App.css, src/App.tsx, src/TASKS.tsx, src/list-components/CentralItemList.tsx, src/list-components/UserList.css, src/list-components/UserList.tsx, src/list-components/adminlist.tsx
prettier display for user and central item list
=> Sullivank list appearance

src/list-components/adminlist.tsx
I changed the way in which we are calling the sort functions so that we always have the most up to date sorted list. The sorted list is now recreated every time before it is displayed, ensuring that all changes made to the tasks are displayed.
=> fixed the editing problem in sorted admin list

src/App.css, src/list-components/DisplayTask.css, src/list-components/UserList.tsx
drop down button that dislays buttons for sorting, also a search button. There are both in the title to make it look better, still working on formating
=> created dropdown for sort buttons, moved search to title

src/list-components/adminlist.tsx
implemented dnd in admin list, can only drag in less than 2 users. we should consider if we really want to drag to admin list, i'm not sure we should have duplicates there
=> drag to admin list only if less than 2 user

src/list-components/adminlist.tsx
fixed the state problem that caused the delete task in adminList to not work
=> fixed state problem in admin list

src/App.css, src/App.tsx, src/pages/AboutPage.tsx, src/pages/dist/home.js, src/pages/taskPage.tsx
Merge conflicts inbound fixed nav bar now we have three pages and cleaned up app.tsx
=> Navbaraaronoster

src/App.tsx, src/index.tsx
This should fix the blank website error
=> fixed minor error found on stack overflow

src/App.tsx
=> trying a new solution to our problem

package.json, src/App.test.tsx, src/CustomRender.tsx, src/dist/App.test.js, src/editing-components/EditTask.test.tsx, src/editing-components/edit-difficulty.test.tsx, src/list-components/CentralItemList.test.tsx, src/list-components/DisplayTask.test.tsx, src/list-components/UserList.test.tsx
Fixed the jest error with drag and drop by adding a configuration to jest in package.json and using a custom render function for all components that use drag and drop. The custom render function wraps the component in a dndProvider which provides the function with the drag and drop context.
=> Cmeiss fix jest error final

src/App.tsx, src/index.tsx
=> Troubleshooting

src/App.tsx
One last thing makes using app clearer to dr harv
=> made usability slightly easier

src/list-components/UserList.tsx
fixed the search bar to not have ugly string
=> fixed the search bar to not have the long ugly string

src/App.tsx
Fixed the homescreen to be more concise
=> fixed homescreen to be better and more clear

src/list-components/adminlist.test.tsx, src/list-components/adminlist.tsx
Added tests for the admin list, tests include testing for displaying only tasks with pendingmode=true, presence and functionality of sorting buttons and displaying admin list only for super and admin.
=> Cmeiss tests admin list

src/App.tsx, src/pages/AboutPage.tsx, src/pages/taskPage.tsx
moved the state from taskpage up to app file to keep changes after switching between pages. State is now passed down from app to taskPage and aboutPage.
=> keep changes after page switching

src/list-components/ModifyUsers.tsx, src/list-components/addTask.tsx, src/list-components/deleteTask-component.tsx, src/list-components/modifyTasksUsers.css, src/pages/taskPage.tsx
got delete task to work and changed display of delete/add task and delete/add user components
=> got delete task component to work

jest.config.js, package-lock.json, package.json, src/App.css, src/list-components/deleteTak.test.tsx
=> Fix tests aaron o

src/App.css, src/App.tsx, src/editing-components/EditStatus.tsx, src/editing-components/EditTask.tsx, src/list-components/CentralItemList.tsx, src/list-components/ChangeRole.tsx, src/list-components/ModifyUsers.tsx, src/list-components/UserList.tsx, src/list-components/addTask.tsx, src/list-components/adminlist.tsx, src/list-components/deleteTask-component.tsx, src/pages/AboutPage.tsx, src/pages/taskPage.tsx
Improved the design of the website:
- added bold font to some components
- changed the color of all blue buttons to a yellow matching our color scheme
- made the navigation bar span across the whole page
- put role select in the navigation bar
- set taskpage as default page so that visitors directly access the main page
=> Cmeiss improve design

src/list-components/ModifyUsers.test.tsx, src/list-components/ModifyUsers.tsx, src/list-components/deleteTask.test.tsx
Fixed all failing tests in modify Users. Fixed last failing tests in delete task while comparing the files to find the issue in modifyUsers.
=> fixed tests in modifyUser and delete task

src/App.test.tsx, src/list-components/deleteTak.test.tsx, src/list-components/deleteTask-component.tsx, src/pages/taskPage.tsx
Here if you delete a task form super or admin it will delete it from any user
=> Delete tasks from super or admin deletes task from user lists too

src/editing-components/EditTask.test.tsx, src/list-components/UserList.tsx, src/list-components/deleteTask-component.tsx, src/list-components/filterlists.test.tsx, src/list-components/modifyTasksUsers.css, src/list-components/searchForUsersWithTask.tsx
fixed the last five failing tests in tsx files and changed the design of search for users with specific a specific task to match the website design better.
=> Cmeiss minor design test fixes
